name: CI - Sistema de Criptografia

on:
  push:
    branches: [ main, master, develop ]
  pull_request:
    branches: [ main, master ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        python-version: ["3.8", "3.9", "3.10", "3.11"]
    
    steps:
    - name: Checkout do código
      uses: actions/checkout@v4
      
    - name: Configurar Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
        
    - name: Instalar dependências
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install pytest
        
    - name: Verificar sintaxe do código
      run: |
        python -m py_compile CRIPTOGRAFIA.py
        echo " Sintaxe do CRIPTOGRAFIA.py verificada"
        
    - name: Executar testes unitários
      run: |
        python -m pytest test_criptografia.py -v --tb=short
